### ISSUE TITLE
Initializing JSONWarehouse

### ISSUE THREAD

**Issue by yismo** [nickoneill/Pantry#22]
I'm having some trouble packing structs. It seems like JSONWarehouse doesn't have any public initializers. I'm the following error from Xcode: "'JSONWarehouse' cannot be constructed because it has no accessible initializers". 

I'm probably just missing something, but creating a JSONWarehouse object doesn't seem to be working. 

Thanks!

**Comment by litso** [comment]
Can i ask why you are trying to init the warehouse directly? If you extend your struct to implement ```Storable``` the warehouse is passed to your structs initializer. (See the Readme)

**Comment by yismo** [comment]
Ah, gotcha - I apologize, I misunderstood that. Also, what exactly should I be doing with the `toDictionary`function? Thanks :)

**Comment by litso** [comment]
Typical use case is that you can ignore it.

**Comment by yismo** [comment]
If I do that though Xcode gives me an error saying my struct doesn't conform to `Storable`.

**Comment by nickoneill** [comment]
@yismo Can you post some of the code you're using to conform to `Storable`?

**Comment by yismo** [comment]
@nickoneill Sure. Here's my struct: 

    struct Person : Storable {
    
    let firstName : String
    let lastName : String
    
    init(warehouse: JSONWarehouse) {
        
        firstName = warehouse.get("firstName") ?? "no first name"
        lastName = warehouse.get("lastName") ?? "no last name"
    }
    
    init(first : String, last : String) {
        firstName = first
        lastName = last
       }
    }

Xcode gives me the following error: `Type 'Person' does not conform to protocol 'Storable'`.

**Comment by jhihguan** [comment]
@yismo Are you using Cocoapods with version 0.2.1?(since the 0.2.1 version doesn't public the extension of toDictionary())
If yes, can you try point to head by
```pod `Pantry`, :head``` and redo a `pod install`
After that you have to change your `init(warehouse: JSONWarehouse)` to `init(warehouse: Warehouseable)`

@nickoneill I think it's better to upgrade version to 0.2.2? the 0.2.1 doesn't workable with Cocoapods

**Comment by nickoneill** [comment]
Oh interesting, thanks for the details @jhihguan. It's frustrating that this stuff isn't caught by tests because the tests are part of the same project. I'll fiddle with this in an attempt to catch these visibility issues upfront.

We'll for sure put out a 0.3 very soon, I want to make sure to get @litso's most recent change in.

**Comment by yismo** [comment]
@jhihguan Thanks! You were right about about the cocapods problem. Adding `:head` seemed to allow everything to work.
