### ISSUE TITLE
Storable extension `toDictionary()` not visible from outside its module

### ISSUE THREAD

**Issue by delannoyk** [nickoneill/Pantry#38]
Hi,

Thank you for the work on this project, it's really helpful!
However, I have an issue with the visibility of `toDictionary()` default implementation in the module. As the default implementation is not `public`, I end up with compilation error:
`Type 'MyType' does not confirm to protocol 'Storable': Protocol requires function 'toDictionary()' with type '() -> [String: AnyObject]'`.
Changing the visibility of the default implementation solves the issue.

**Comment by delannoyk** [comment]
That is also true for `StorableRawEnum` implementation.

**Comment by nickoneill** [comment]
Hey @delannoyk, this is fixed but we haven't made a new release with the changes yet. Feel free to use `:head` if you're on cocoapods or `master` with carthage to get the newest changes beyond the current release.

**Comment by delannoyk** [comment]
Hi @nickoneill 
Indeed! Thanks.

**Comment by charlag** [comment]
First of all, thanks for your work. But I think that this bug prevents people from using this library. You download it - and it's broken. Adding just one word fixes it - why not add this fix?

**Comment by nickoneill** [comment]
Appreciate your feedback @charlag but creating a new release that other people may pull into their published projects requires a bit more time and thought that just "adding just one word". What about testing any other changes that have been introduced into master since the last release?

It makes much more sense for you to add your "one word fix" (i.e. the `:head` or `master` change noted above) in *your* podfile if you need it in the short term than for this project to force a potentially unready change on *everyone* who depends on Pantry.
